name: Deploy Docs

on:
  push:
    tags:

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Configure git user
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run:
        pdm install --skip post_install
    - name: Bump Version number
      run: |
        eval $(pdm venv activate)
        version="$(cz version --project | sed -E 's/([0-9]+)\.([0-9]+)\.[0-9]+/\1.\2.x/g')"
        mike deploy --push --update-aliases --alias-type redirect $version latest
